### ISSUE TITLE
Simple Question) Is this can be used for normal drawing  by PIL?

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [tomicapretto/flexitext#13]
Hi.
It is nice package. Thanks.
Is this can be used for normal drawing  by PIL for nomal drawing purpose without plt?

**Comment by tomicapretto** [comment]
Hi @Mitchell-kw-Lee, thanks for the kind words. There are some lower-level components that are not tied to Matplotlib (i.e. everything here https://github.com/tomicapretto/flexitext/tree/main/flexitext/parser). But, ultimately, the library assumes you want to use Matplotlib to create your visualizations.

**Comment by Mitchell-kw-Lee** [comment]
@tomicapretto Thanks for the guide.
Erm...then, 
If I do the code pseudo snipet as below, can be use as I want overally?
---------------
import PIL

image = Image.new()
handle = image.draw()
text = "<color:blue, size:16>This is blue text</> and this is regular text"
flexitext(handle, text)
-------------

What am I missing?
How to interface PIL image object and flexitext, could you show me the overall way to archive the goal?

**Comment by tomicapretto** [comment]
Unfortunately, that's not going to work, and I think it would require a non-trivial amount of work to make `flexitext` support a PIL backend as things are written using features of Matplotlib.

**Comment by Mitchell-kw-Lee** [comment]
@tomicapretto 
Thanks to know. Have a good day.
