### ISSUE TITLE
plt.subplots?

### ISSUE THREAD

**Issue by JiWenzheng** [tomicapretto/flexitext#6]
Hi, I want to use Flexitext to draw the text of subplots, but I find that parameter **_transform = axes. TransAxes_** is not supported. Is it possible to specify coordinate system in the future?

**Comment by tomicapretto** [comment]
Do you mean something like this?

```python
import matplotlib.pyplot as plt
from flexitext import flexitext

fig, ax = plt.subplots(1, 2, figsize=(12, 6))

text1 = "<size:42, name:Calibri>Some<color:#11557c, weight:bold> text</></>"
text2 = "<size:36, name:Lato, color:royalblue><weight:bold>Here</> too</>"

flexitext(0.5, 0.5, text1, ha="center", ax=ax[0])
flexitext(0.5, 0.5, text2, ha="center", ax=ax[1])

fig.set_facecolor("w")
fig.savefig("example.png", dpi=300)
```

![example](https://user-images.githubusercontent.com/25507629/137585942-e562ae9b-2b42-4e25-b52f-9270eaaa4492.png)

**Comment by JiWenzheng** [comment]
Thank you, I understand how to deal with it, it seems that my understanding of matplotlib needs to be improved.
