### ISSUE TITLE
About flexitext parameter "ha" and "va"

### ISSUE THREAD

**Issue by JiWenzheng** [tomicapretto/flexitext#7]
Hello author, the **ha** and **va** parameters in the flexitext library do not seem to be consistent with those in **ax.text**. Set **ha='center'** in **ax.text**, the text of different lines will be aligned in the center, but this parameter seems to be invalid in flexitext (The alignment result is not quite consistent with the text). Setting ha='center' in flexitext is still left-aligned?  The following is my code: 

`    

    fig.subplots_adjust(top=0.8, left=0.025)
    x = [1, 2, 3]
    y_blue = [2, 2.7, 4.5]
    y_red = [1, 3, 2.5]
    ax.scatter(x, y_blue, color="royalblue", s=120)
    ax.scatter(x, y_red, color="crimson", s=120)
    # Add flexitext
    text = (
        "<name:Montserrat><size:24>A <weight:bold>great chart</> showing</>\n"
        "<size:18>the values for the "
        "<color:royalblue, weight:bold>blues</> and the <color:crimson, weight:bold>reds</></></>"
    )
    flexitext(0.5, 0.5, text, va="center", ha='center', ax=ax); #xycoords="figure fraction"
    ax.text(0.5, 0.2, text, va="center", ha='center',transform=ax.transAxes)
    plt.show()

`

![image](https://user-images.githubusercontent.com/90814014/137592737-5c7e6bde-9488-41b2-aff6-b63bcde83f08.png)
Is there a parameter in flexitext that can horizontally align the text of different lines in the center (even if the text size is inconsistent)?

Thank you.

**Comment by tomicapretto** [comment]
You want to use `ma`. Have a look at the docs [here](https://tomicapretto.github.io/flexitext/reference/flexitext/).

**Comment by JiWenzheng** [comment]
Thank you for your suggestion. I have another question. In a line of rich text, the text size is inconsistent, and the alignment of flexitext seems to be centered by default. As shown in the figure below, is there any parameter to align "**the values for the**" and "**blues**" at the bottom? **ha** does not seem to be able to achieve this effect?
![image](https://user-images.githubusercontent.com/90814014/137594506-132934d0-612a-49bc-b4bf-9561233888ee.png)

**Comment by tomicapretto** [comment]
I think it is not possible to do that at the moment. I need to fix some internals first #8

**Comment by tomicapretto** [comment]
@JiWenzheng, this issue is fixed in 5da272172874fc89e54c4bf112a237dadb37062a.
